# Generated by Django 4.1.1 on 2023-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_0', models.CharField(max_length=100, verbose_name='Item_0')),
                ('item_1', models.CharField(max_length=100, verbose_name='Item_1')),
                ('item_2', models.CharField(max_length=100, verbose_name='Item_2')),
                ('item_3', models.CharField(max_length=100, verbose_name='Item_3')),
                ('item_4', models.CharField(max_length=100, verbose_name='Item_4')),
                ('item_5', models.CharField(max_length=100, verbose_name='Item_5')),
                ('item_6', models.CharField(max_length=100, verbose_name='Item_6')),
                ('item_7', models.CharField(max_length=100, verbose_name='Item_7')),
                ('item_8', models.CharField(max_length=100, verbose_name='Item_8')),
            ],
        ),
    ]
